name: "🚀 Feature Request"
description: Suggest a new feature or improvement
title: "[FEATURE] <short description>"
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your idea! Please help us understand your feature request.
  - type: input
    id: summary
    attributes:
      label: Feature Summary
      description: A concise description of your idea
      placeholder: Add dark mode support
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve?
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your proposed solution or API design
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered other options or libraries?
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any context, mockups, or screenshots
